# Generated by Django 5.0.6 on 2024-05-31 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('price_per_person', models.IntegerField()),
                ('popular', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.PositiveIntegerField(default=0)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('kids', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Destination_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField()),
                ('main_image', models.ImageField(upload_to='mymedia')),
                ('image2', models.ImageField(blank=True, upload_to='mymedia')),
                ('image3', models.ImageField(blank=True, upload_to='mymedia')),
                ('image4', models.ImageField(blank=True, upload_to='mymedia')),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_dinner', models.BooleanField(default=True)),
                ('has_tub', models.BooleanField(default=True)),
                ('has_pool', models.BooleanField(default=True)),
                ('destinationid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.destination')),
            ],
        ),
    ]
