# Generated by Django 5.0.2 on 2024-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='child',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='kids',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
