# Generated by Django 5.0.2 on 2024-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_destination_detail_destinationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='adults',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='child',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='kids',
            field=models.PositiveIntegerField(),
        ),
    ]
